export const LOGGED_IN = "LOGGED_IN";
export const ADDED_BLOCKERS = "ADDED_BLOCKERS";
export const COMPLETED_BLOCKER = "COMPLETED_BLOCKER";
export const LOADED_BLOCKERS = "LOADED_BLOCKERS";

// export const SIGNUP_WATCHER = "SIGNUP_WATCHER";
// export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
// export const SIGNUP_ERROR = "SIGNUP_ERROR";
// export const CONFIRM_USER_WATCHER = "CONFIRM_USER_WATCHER";
// export const CONFIRM_USER_SUCCESS = "CONFIRM_USER_SUCCESS";
// export const LOGIN_WATCHER = "LOGIN_WATCHER";
// export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
// export const LOGIN_ERROR = "LOGIN_ERROR"; 
