export const LOGGED_IN = "LOGGED_IN";
export const ADDED_BLOCKERS = "ADDED_BLOCKERS";
export const COMPLETED_BLOCKER = "COMPLETED_BLOCKER";
export const COMPLETED_SUGGESTION = "COMPLETED_SUGGESTION";
export const RESET_PROGRESS = "RESET_PROGRESS";