import "react-native-get-random-values";
import { v4 as v4 } from "uuid";

export default function initBlockers() {
  return {
    currentPoints: {
      exercise: 0,
      music: 0,
      social: 0,
    },
    blockers: [
      {
        category: "exercise",
        id: v4(),
        description: "Do you have running shoes?",
        createdAt: new Date(),
        completedAt: null,
        points: 10,
        color: "#D8A1D5",
        suggestions: [
          {
            id: v4(),
            description: "Go for a 1 mile jog",
            createdAt: new Date(),
            completedAt: null,
            points: 20,
            color: "#D8A1D5",
          },
          {
            id: v4(),
            description: "Go for a 3 mile run",
            createdAt: new Date(),
            completedAt: null,
            points: 30,
            color: "#D8A1D5",
          },
        ],
      },
      {
        category: "exercise",
        id: v4(),
        description: "Do you have a bike?",
        createdAt: new Date(),
        completedAt: null,
        points: 20,
        color: "#D8A1D5",
        suggestions: [
          {
            id: v4(),
            description: "Go for a 1 mile bike",
            createdAt: new Date(),
            completedAt: null,
            points: 20,
            color: "#D8A1D5",
          },
          {
            id: v4(),
            description: "Go for a 3 mile bike",
            createdAt: new Date(),
            completedAt: null,
            points: 30,
            color: "#D8A1D5",
          },
        ],
      },
      {
        category: "exercise",
        id: v4(),
        description: "Do you have a yoga mat?",
        createdAt: new Date(),
        completedAt: null,
        points: 30,
        color: "#D8A1D5",
        suggestions: [
          {
            id: v4(),
            description: "Do 15 mins yoga",
            createdAt: new Date(),
            completedAt: null,
            points: 20,
            color: "#D8A1D5",
          },
          {
            id: v4(),
            description: "Do 30 mins yoga",
            createdAt: new Date(),
            completedAt: null,
            points: 30,
            color: "#D8A1D5",
          },
        ],
      },
      {
        category: "music",
        id: v4(),
        description: "Do you know how to make a playlist?",
        createdAt: new Date(),
        completedAt: null,
        points: 10,
        color: "#94D7B5",
        suggestions: [
          {
            id: v4(),
            description: "...",
            createdAt: new Date(),
            completedAt: null,
            points: 20,
            color: "#D8A1D5",
          },
          {
            id: v4(),
            description: "......",
            createdAt: new Date(),
            completedAt: null,
            points: 30,
            color: "#D8A1D5",
          },
        ],
      },
      {
        category: "music",
        id: v4(),
        description: "Are you folowing multiple artists?",
        createdAt: new Date(),
        completedAt: null,
        points: 20,
        color: "#94D7B5",
        suggestions: [
          {
            id: v4(),
            description: "...",
            createdAt: new Date(),
            completedAt: null,
            points: 20,
            color: "#D8A1D5",
          },
          {
            id: v4(),
            description: "......",
            createdAt: new Date(),
            completedAt: null,
            points: 30,
            color: "#D8A1D5",
          },
        ],
      },
      {
        category: "music",
        id: v4(),
        description: "Do you follow other users?",
        createdAt: new Date(),
        completedAt: null,
        points: 30,
        color: "#94D7B5",
        suggestions: [
          {
            id: v4(),
            description: "...",
            createdAt: new Date(),
            completedAt: null,
            points: 20,
            color: "#D8A1D5",
          },
          {
            id: v4(),
            description: "......",
            createdAt: new Date(),
            completedAt: null,
            points: 30,
            color: "#D8A1D5",
          },
        ],
      },
      {
        category: "social",
        id: v4(),
        description: "Do you...?",
        createdAt: new Date(),
        completedAt: null,
        points: 10,
        color: "#E0C45E",
        suggestions: [
          {
            id: v4(),
            description: "...",
            createdAt: new Date(),
            completedAt: null,
            points: 20,
            color: "#D8A1D5",
          },
          {
            id: v4(),
            description: "......",
            createdAt: new Date(),
            completedAt: null,
            points: 30,
            color: "#D8A1D5",
          },
        ],
      },
      {
        category: "social",
        id: v4(),
        description: "Are you...?",
        createdAt: new Date(),
        completedAt: null,
        points: 20,
        color: "#E0C45E",
        suggestions: [
          {
            id: v4(),
            description: "...",
            createdAt: new Date(),
            completedAt: null,
            points: 20,
            color: "#D8A1D5",
          },
          {
            id: v4(),
            description: "......",
            createdAt: new Date(),
            completedAt: null,
            points: 30,
            color: "#D8A1D5",
          },
        ],
      },
      {
        category: "social",
        id: v4(),
        description: "Do you have...?",
        createdAt: new Date(),
        completedAt: null,
        points: 30,
        color: "#E0C45E",
        suggestions: [
          {
            id: v4(),
            description: "...",
            createdAt: new Date(),
            completedAt: null,
            points: 20,
            color: "#D8A1D5",
          },
          {
            id: v4(),
            description: "......",
            createdAt: new Date(),
            completedAt: null,
            points: 30,
            color: "#D8A1D5",
          },
        ],
      },
    ],
  };
}
